import Navbar from "@components/Navbar";
import "@styles/globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="bg-OpenColor-gray-0 text-OpenColor-gray-7">
				<Navbar />
				<main className="grid grid-cols-12 container mx-auto">{children}</main>
			</body>
		</html>
	);
}
